name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    permissions:
      id-token: write # for AWS OIDC

    strategy:
      matrix:
        include:
          - runner: buildjet-4vcpu-ubuntu-2204
            arch: amd64
          - runner: buildjet-4vcpu-ubuntu-2204-arm
            arch: arm64

    runs-on: ${{matrix.runner}}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to AWS
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::970625735569:role/GitHubActionsECRPush

      - name: Configure AWS Docker Auth
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          registry-type: public

      - name: Generate Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            public.ecr.aws/edgebit/cluster-agent
          tags: |
            type=ref,event=pr,suffix=-${{ matrix.arch }}
          flavor: |
            latest=false

      - id: build
        name: Building agent
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Generate SBOM from the container
        if: ${{ matrix.arch == 'amd64' }}
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.build.outputs.imageid }}
          artifact-name: sbom.spdx.json
          upload-artifact: true
          config: .github/edgebit/build-syft.yaml

      - name: Save metadata to an artifact
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          cat > /tmp/metadata.json <<EOF
            {
              "commit-sha": "${{ github.sha }}",
              "image-id": "${{ steps.build.outputs.imageid }}",
              "image-tag": "${{ steps.meta.outputs.tags }}",
              "pr-number": "${{ github.event.number }}",
              "tags": "${{ github.ref == 'refs/heads/main' && 'latest' || '' }}"
            }
          EOF

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.arch == 'amd64' }}
        with:
          name: metadata.json
          path: /tmp/metadata.json
